databases:
  - name: byteleafdb          # Render’s internal handle for the database
    plan: free
    databaseName: byteleafdb  # actual Postgres database name
    user: byteleaf            # the DB user Render will create

services:
  - type: web
    plan: free
    name: byteleaf            # your Render service name
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn byteleaf.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: byteleafdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
