# Generated by Django 5.2.3 on 2025-06-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('ip_lat', models.FloatField(blank=True, null=True)),
                ('ip_lon', models.FloatField(blank=True, null=True)),
                ('ip_city', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('all_info', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
