# Generated by Django 5.2.3 on 2025-06-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerloc',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customerloc',
            name='longitude',
        ),
        migrations.AddField(
            model_name='customerloc',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerloc',
            name='gps_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerloc',
            name='ip_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerloc',
            name='ip_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerloc',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerloc',
            name='link_clicks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customerloc',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerloc',
            name='uid',
            field=models.CharField(default='', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerloc',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
