# Generated by Django 5.2.3 on 2025-06-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0002_remove_customerloc_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerloc',
            name='link_clicks',
        ),
        migrations.RemoveField(
            model_name='customerloc',
            name='uid',
        ),
        migrations.AlterField(
            model_name='customerloc',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
