# Generated by Django 5.2.3 on 2025-06-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0003_remove_customerloc_link_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloc',
            name='ip_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
